version: '3'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=test

  app-production: &production
    build:
      context: .
      args:
        - BUILD_HASH=${BUILDKITE_COMMIT}

  app-staging:
    <<: *production
