version: '3'

services:
  app:
    build:
      context: .

  app-production:
    build:
      context: .
      args:
        - NODE_ENV=production
        - BUILD_HASH=${BUILDKITE_COMMIT}

  app-staging:
    build:
      context: .
      args:
        - NODE_ENV=staging
        - BUILD_HASH=${BUILDKITE_COMMIT}
