version: '3'

services:
  db:
    image: postgres:11.2
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nsadmin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nsadmin-api:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nodejs
    networks:
      - nsadmin_production_default

networks:
  nsadmin_production_default:
    external: true

volumes:
  postgres_data:
