version: '3'

services:
  app:
    build: .
    image: nsadmin-api
    container_name: nsadmin-api
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
    networks:
      - nsadmin_production_default
    command: /bin/bash ./bin/wait-for-it.sh db:5432 -- npm start

  db:
    image: postgres:11.2
    container_name: postgres-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: nsadmin_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nsadmin_production_default

networks:
  nsadmin_production_default:
    external: true

volumes:
  node_modules:
  postgres_data:
