version: '3'

services:
  app:
    image: docker.guidojw.nl/arora/arora-api:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
    volumes:
      - /opt/app/node_modules
      - ./private.key:/opt/app/private.key
      - ./public.key:/opt/app/public.key
    labels:
      - traefik.enable=true
      - traefik.http.routers.arora-api-production.rule=Host(`$HOST`) && PathPrefix(`/api`)
      - traefik.http.routers.arora-api-production.middlewares=api-strip@file
      - traefik.http.routers.arora-api-production.tls.certresolver=default
    command: /bin/bash ./bin/wait-for-it.sh db:5432 -- yarn start

  db:
    image: postgres:11.2
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
