export { default as AuthService } from './auth'
export { default as BanService } from './ban'
export { default as CatalogService } from './catalog'
export { default as GroupService } from './group'
export { default as ExileService } from './exile'
export { default as StatusService } from './status'
export { default as TrainingService } from './training'
export { default as UserService } from './user'
