name: Cleanup Registry

on:
  schedule:
    - cron: '0 0 * * 1' # https://crontab.guru/#0_0_*_*_1
  workflow_dispatch:

env:
  IMAGE_NAMES: arora-api

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions
        uses: snok/container-retention-policy@482ce28159f65a8bfad986da1fedcef40169aa75 # v2.0.0
        with:
          image-names: ${{ env.IMAGE_NAMES }}
          cut-off: 2 days ago UTC
          account-type: personal
          skip-tags: latest,staging
          token: ${{ secrets.PAT }}
