name: Cleanup Registry

on:
  schedule:
    - cron: '0 0 * * 1' # https://crontab.guru/#0_0_*_*_1
  workflow_dispatch:

env:
  IMAGE_NAMES: arora-api

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions
        uses: snok/container-retention-policy@f617f1ca161a52bce48417eedd76924e71d0b4d9 # v2.1.0
        with:
          image-names: ${{ env.IMAGE_NAMES }}
          cut-off: 2 days ago UTC
          account-type: personal
          skip-tags: latest,staging
          token: ${{ secrets.GH_PAT }}
