name: Continuous Integration

on:
  push:
    branches: [staging, main]
  pull_request:
  workflow_call:
    inputs:
      sha:
        required: false
        type: string

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/tsc.json'

      - name: Build test image
        uses: guidojw/actions/build-docker-image@v1
        with:
          name: app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/eslint-stylish.json'

      - name: Load test image
        uses: guidojw/actions/load-docker-image@v1
        with:
          name: app

      - name: Lint
        run: |
          docker run app yarn lint
