name: Continuous Integration

on:
  push:
    branches: [staging, main]
  pull_request:
  workflow_call:
    inputs:
      sha:
        description: The commit SHA to run the workflow on
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ inputs.sha }}

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/tsc.json'

      - name: Build test image
        uses: guidojw/actions/build-docker-image@5faa9418b42a6a77f81e11ae935287900673f98b # tag=v1.3.2
        with:
          name: app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ inputs.sha }}

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/actionlint.json'
          echo '::add-matcher::.github/problem-matchers/eslint-stylish.json'

      - name: Download actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Load test image
        uses: guidojw/actions/load-docker-image@5faa9418b42a6a77f81e11ae935287900673f98b # tag=v1.3.2
        with:
          name: app

      - name: Lint
        run: |
          EXIT_STATUS=0
          ./actionlint -ignore 'property "app_private_key" is not defined' -ignore 'SC2153:' || EXIT_STATUS=$?
          docker run app yarn lint || EXIT_STATUS=$?
          exit $EXIT_STATUS
